name = "Lean4TaskManager"
version = "0.1.0"

[[lean_lib]]
name = "Lean4TaskManager"

# A Git dependency
[[require]]
name = "Lean4MyLib"
git = "https://github.com/shinamon610/Lean4MyLib"
rev = "df7d044f3c6426ef0051f17995147af11ccb9355"